### ISSUE TITLE
Can't read/write from/to default input/output file

### ISSUE THREAD

**Issue by petrbel** [iterait/shepherd#34]
It happened just now, out of nowhere.
```
2018-10-19 11:48:09.588: ERROR   @base_runner : [Errno 2] No such file or directory: '/tmp/shepherd-data/bare_sheep/d15c23aa-39b8-4d1a-88ff-e8e09fbc8734/outputs/output'                                                                                                   
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/shepherd/runner/base_runner.py", line 128, in process_all
    self._process_job(input_path, output_path)
  File "/isletnet/model/isletnet_runner.py", line 177, in _process_job
    with open(path.join(output_path, DEFAULT_OUTPUT_FILE), 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/shepherd-data/bare_sheep/d15c23aa-39b8-4d1a-88ff-e8e09fbc8734/outputs/output'                                                                                                                                
2018-10-19 11:48:09.588: ERROR   @base_runner : Sending ErrorMessage for job `d15c23aa-39b8-4d1a-88ff-e8e09fbc8734
```

After another payload, even reading the input file fails. Any ideas @Teyras @FloopCZ @blazekadam ?

**Comment by FloopCZ** [comment]
@petrbel was this related to conflicting running instances of shepherd or is it still relevant?

**Comment by petrbel** [comment]
Both. I mean, the issue is fixed, however, we still want to report that runner has failed (regardless weird reasons such as multiple shpeherd instances).

**Comment by Teyras** [comment]
I suggest we close this and make a new issue for that.

**Comment by petrbel** [comment]
Be my guest, however, we should describe at least one way of reproducing the error (e.g. run two shepherds).
