### ISSUE TITLE
ConnectionResetError while running load tests

### ISSUE THREAD

**Issue by gdynusa** [iterait/shepherd#63]
Related to #55 
```
Traceback (most recent call last):
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 447, in start
    await resp.prepare(request)
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/web_response.py", line 353, in prepare
    return await self._start(request)
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/web_response.py", line 667, in _start
    return await super()._start(request)
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/web_response.py", line 410, in _start
    await writer.write_headers(status_line, headers)
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/http_writer.py", line 112, in write_headers
    self._write(buf)
  File "/home/gdynusa/.pyenv/versions/3.7.2/envs/shepherd/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

**Comment by blazekadam** [comment]
It's a feature :D (https://github.com/iterait/shepherd/pull/55#issuecomment-457834456)
